// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqOVTtCkNbhv__xe73-ZSuPcOnNpVvR5k',
    appId: '1:59385363502:web:cccca849a0fd5691cd33bf',
    messagingSenderId: '59385363502',
    projectId: 'swiggy-varun',
    authDomain: 'swiggy-varun.firebaseapp.com',
    storageBucket: 'swiggy-varun.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfWlRrPUYL7_0ZxDT8d9DbaVAkknbSvAU',
    appId: '1:59385363502:android:b0daa9bf144a4169cd33bf',
    messagingSenderId: '59385363502',
    projectId: 'swiggy-varun',
    storageBucket: 'swiggy-varun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNutha_d3QFMMLIJ36dYrcvT8qChdR5yM',
    appId: '1:59385363502:ios:e8e1e9d9effcc276cd33bf',
    messagingSenderId: '59385363502',
    projectId: 'swiggy-varun',
    storageBucket: 'swiggy-varun.appspot.com',
    iosBundleId: 'com.example.swiggy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNutha_d3QFMMLIJ36dYrcvT8qChdR5yM',
    appId: '1:59385363502:ios:baa9e284d0a42cf0cd33bf',
    messagingSenderId: '59385363502',
    projectId: 'swiggy-varun',
    storageBucket: 'swiggy-varun.appspot.com',
    iosBundleId: 'com.example.swiggy.RunnerTests',
  );
}
